### PR TITLE
Mortars cleanup

### LINKED ISSUE #49: Major Mortar elevation bug
There is a bug with all the mortars  that locks them at a specific elevation making them unusable. Basically if there is a round loaded in the tube you cant increase elevation about a certain point, for the 60mm the max elevation is 1375. This means you cant hit targets between 500 and 850 meters as it is impossible to get the elevation set to those ranges. This makes the mortars basically unusable. When a round is unloaded you can increase the elevation all the way up to 1500 something. Also everytime you load a round your elevation resets, rather annoying, but bearable. 

Loaded mods - https://gyazo.com/a166fadc226da3b797b78133c4b89a86

Sudo steps to reproduce - Right, so I place down the M2 60mm Mortar from IFA3 (it says ACE in its name) and then I can bring the elevation all the way up to 1500. But once a mortar round is put in the tube (by ace interacting on the barrel) the mortar changes elevation and is capped at 1375 for the elevation.

### LINKED ISSUE #51: Shell bug with mortar Problem
Are a big bug with the mortars and ace. When a mortar are spawned in the editor, it look ok, and you can full interact with it (like edit his parameters) but in game, it spawn with 32 81 mm Explosive shells, 8 Smoke shells and 8 ligth shells arround it. It bugs the sistem and you can reload or change the shell. when you dismount it th spawned shells stay here and when you mount in another location, new shells apear in the mortar nearbies. If you need a video or images, i can send it.

### PR DESCRIPTION
**Pull request by ElTyranos**
**Don't merge yet - this PR is for co-working**

TODO : 
- [x] Get rid of inherited UserActions
- [x] ACE ammo handling does not work
- [x] Check https://github.com/bux/IFA3_ACE_COMPAT/issues/49
- [x] Confirm https://github.com/bux/IFA3_ACE_COMPAT/issues/51 is gone

Notes:
* It uses ACE CSW entirely for assembly/disassembly so don't do it like vanilla IFA3, you need to use self-interact to deploy the tripod, and interact with it to assemble.

Known issues:
* If you place a mortar down in the editor you wont be able to disassemble it unless 'advanced assembly' is enabled, and doing so will probably break AI as it makes all the stored ammo appear next to the mortar.

### CODE REVIEW

File: addons/mortar/CfgVehicles.hpp [hunk 1]
```diff
@@ -1,206 +1,51 @@
...
-			base = "";
-			assembleTo = "";
-			dissasembleTo[] = {};
-			displayName = "";
-		};
-		class ACE_Actions;
+	class LIB_StaticMortar_base;
+	class LIB_SU_Mortar_base: LIB_StaticMortar_base {};
+	class LIB_BM37: LIB_SU_Mortar_base {
+		class UserActions {};
```
Comment (ElTyranos) [inline addons/mortar/CfgVehicles.hpp]: This doesn't cleanup the existing UserActions (prepare round etc.)

**Comment by kerckasha** [comment]
Ammo handling etc works fine for me with current commit, needs to be tested
